export const CATEGORIAS = {
    Cachorro: ['SRD', 'Poodle', 'Bulldog', 'Labrador'],
    Gato: ['SRD', 'Siamês', 'Persa', 'Maine Coon'],
    Aves: ['Calopsita', 'Papagaio', 'Canário'],
    Outros: ['Coelho', 'Hamster', 'Tartaruga']
};

export const TRANSLATIONS = {
    pt: {
        feed: 'Feed',
        newPost: 'Novo Post',
        settings: 'Configurações',
        login: 'Entrar',
        logout: 'Sair',
        theme: 'Tema',
        language: 'Idioma',
        server: 'Servidor',
        dark: 'Escuro',
        light: 'Claro',
        save: 'Salvar',
        publish: 'Publicar',
        gallery: 'Galeria',
        camera: 'Câmera',
        descPlace: 'Descreva a foto...',
        category: 'Categoria',
        breed: 'Raça',
        name: 'Nome',
        email: 'E-mail',
        serverPlace: 'URL do Servidor (ex: http://ip:5000)',
        sortNewest: 'Mais Recentes',
        sortLikes: 'Mais Curtidos',
        loadMore: 'Carregar Mais',
        welcome: 'Bem-vindo ao Animals Picture',
        welcomeDesc: 'Compartilhe fotos dos seus pets',
        loginPrompt: 'Faça login para curtir',
        imageRequired: 'Imagem e descrição obrigatórios',
        noServer: 'Erro no Servidor',
        postCreated: 'Publicação criada'
    },
    en: {
        feed: 'Feed',
        newPost: 'New Post',
        settings: 'Settings',
        login: 'Login',
        logout: 'Logout',
        theme: 'Theme',
        language: 'Language',
        server: 'Server',
        dark: 'Dark',
        light: 'Light',
        save: 'Save',
        publish: 'Publish',
        gallery: 'Gallery',
        camera: 'Camera',
        descPlace: 'Describe the photo...',
        category: 'Category',
        breed: 'Breed',
        name: 'Name',
        email: 'Email',
        serverPlace: 'Server URL',
        sortNewest: 'Newest',
        sortLikes: 'Most Liked',
        loadMore: 'Load More',
        welcome: 'Welcome',
        welcomeDesc: 'Share your pets',
        loginPrompt: 'Login to like',
        imageRequired: 'Image and description required',
        noServer: 'Server Error',
        postCreated: 'Post created'
    },
    es: {
        feed: 'Inicio',
        newPost: 'Nuevo Post',
        settings: 'Ajustes',
        login: 'Entrar',
        logout: 'Salir',
        theme: 'Tema',
        language: 'Idioma',
        server: 'Servidor',
        dark: 'Oscuro',
        light: 'Claro',
        save: 'Guardar',
        publish: 'Publicar',
        gallery: 'Galería',
        camera: 'Cámara',
        descPlace: 'Describe la foto...',
        category: 'Categoría',
        breed: 'Raza',
        name: 'Nombre',
        email: 'Correo',
        serverPlace: 'URL del Servidor',
        sortNewest: 'Recientes',
        sortLikes: 'Me Gusta',
        loadMore: 'Cargar Más',
        welcome: 'Bienvenido',
        welcomeDesc: 'Comparte a tus mascotas',
        loginPrompt: 'Inicia sesión',
        imageRequired: 'Imagen obligatoria',
        noServer: 'Error en servidor',
        postCreated: 'Post creado'
    }
};
