export const CATEGORIAS = {
    Perdidos: ['Cachorro', 'Gato', 'Ave', 'Outro'],
    Encontrados: ['Cachorro', 'Gato', 'Ave', 'Outro'],
    Adoção: ['Cachorro', 'Gato', 'Ave', 'Outro']
};

export const TRANSLATIONS = {
    pt: {
        feed: 'Feed',
        newPost: 'Novo Post',
        settings: 'Configurações',
        login: 'Entrar',
        logout: 'Sair',
        theme: 'Tema',
        language: 'Idioma',
        server: 'Servidor',
        dark: 'Escuro',
        light: 'Claro',
        save: 'Salvar',
        publish: 'Publicar',
        gallery: 'Galeria',
        camera: 'Câmera',
        descPlace: 'Descreva o animal (nome, cor, local visto...)',
        category: 'Categoria',
        breed: 'Tipo de Animal',
        name: 'Nome',
        email: 'E-mail',
        serverPlace: 'URL do Servidor (ex: http://ip:5000)',
        sortNewest: 'Mais Recentes',
        sortLikes: 'Mais Curtidos',
        loadMore: 'Carregar Mais',
        welcome: 'Ajude a Reunir Famílias 🐾',
        welcomeDesc: 'Nossa missão é usar o poder da comunidade para encontrar animais perdidos, promover adoções responsáveis e salvar vidas. Faça parte!',
        loginPrompt: 'Faça login para curtir',
        imageRequired: 'Imagem e descrição obrigatórios',
        noServer: 'Erro no Servidor',
        postCreated: 'Publicação criada',
        donate: 'Doar',
        donateTitle: 'Faça a Diferença! 💛',
        donateDesc: 'Considere doar para a AMPARA Animal, uma das maiores redes de apoio a protetores e animais abandonados do Brasil. Qualquer valor salva vidas.',
        donateBtn: 'Doar para AMPARA Animal 🐾',
        donateDisclaimer: 'A Animals Picture não retém nenhuma parte das doações. Você será redirecionado ao site oficial da ONG.',
        Perdidos: 'Perdidos',
        Encontrados: 'Encontrados',
        Adoção: 'Adoção',
    },
    en: {
        feed: 'Feed',
        newPost: 'New Post',
        settings: 'Settings',
        login: 'Login',
        logout: 'Logout',
        theme: 'Theme',
        language: 'Language',
        server: 'Server',
        dark: 'Dark',
        light: 'Light',
        save: 'Save',
        publish: 'Publish',
        gallery: 'Gallery',
        camera: 'Camera',
        descPlace: 'Describe the animal (name, color, location seen...)',
        category: 'Category',
        breed: 'Animal Type',
        name: 'Name',
        email: 'Email',
        serverPlace: 'Server URL',
        sortNewest: 'Newest',
        sortLikes: 'Most Liked',
        loadMore: 'Load More',
        welcome: 'Help Reunite Families 🐾',
        welcomeDesc: 'Our mission is to use community power to find lost animals, promote responsible adoptions, and save lives. Join us!',
        loginPrompt: 'Login to like',
        imageRequired: 'Image and description required',
        noServer: 'Server Error',
        postCreated: 'Post created',
        donate: 'Donate',
        donateTitle: 'Make a Difference! 💛',
        donateDesc: 'Consider donating to AMPARA Animal, one of the largest animal protection support networks in Brazil. Any amount saves lives.',
        donateBtn: 'Donate to AMPARA Animal 🐾',
        donateDisclaimer: 'Animals Picture does not retain any part of the donations. You will be redirected to the official NGO website.',
        Perdidos: 'Lost',
        Encontrados: 'Found',
        Adoção: 'Adoption',
    },
    es: {
        feed: 'Inicio',
        newPost: 'Nuevo Post',
        settings: 'Ajustes',
        login: 'Entrar',
        logout: 'Salir',
        theme: 'Tema',
        language: 'Idioma',
        server: 'Servidor',
        dark: 'Oscuro',
        light: 'Claro',
        save: 'Guardar',
        publish: 'Publicar',
        gallery: 'Galería',
        camera: 'Cámara',
        descPlace: 'Describe el animal (nombre, color, ubicación...)',
        category: 'Categoría',
        breed: 'Tipo de Animal',
        name: 'Nombre',
        email: 'Correo',
        serverPlace: 'URL del Servidor',
        sortNewest: 'Recientes',
        sortLikes: 'Me Gusta',
        loadMore: 'Cargar Más',
        welcome: 'Ayuda a Reunir Familias 🐾',
        welcomeDesc: 'Nuestra misión es usar el poder de la comunidad para encontrar animales perdidos, promover adopciones responsables y salvar vidas.',
        loginPrompt: 'Inicia sesión',
        imageRequired: 'Imagen obligatoria',
        noServer: 'Error en servidor',
        postCreated: 'Post creado',
        donate: 'Donar',
        donateTitle: '¡Haz la Diferencia! 💛',
        donateDesc: 'Considera donar a AMPARA Animal, una de las mayores redes de apoyo a protectores y animales abandonados de Brasil.',
        donateBtn: 'Donar a AMPARA Animal 🐾',
        donateDisclaimer: 'Animals Picture no retiene ninguna parte de las donaciones.',
        Perdidos: 'Perdidos',
        Encontrados: 'Encontrados',
        Adoção: 'Adopción',
    }
};
